.TH "C:/Users/lasse/Documents/Visual Studio 2015/Projects/TickTackToe/TickTackToe/Properties/AssemblyInfo.cs" 3 "Sun Feb 26 2017" "Version 1.0.0" "TicTacToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/lasse/Documents/Visual Studio 2015/Projects/TickTackToe/TickTackToe/Properties/AssemblyInfo.cs
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for TicTacToe from the source code\&.
