.TH "TickTackToe" 3 "Sun Feb 26 2017" "Version 1.0.0" "TicTacToe" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TickTackToe
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGame\fP"
.br
.RI "\fBGame\fP logic for tic tac toe game "
.ti -1c
.RI "class \fBProgram\fP"
.br
.RI "Main Class "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TicTacToe from the source code\&.
